### ISSUE TITLE
The special mana block is not generate (last version)

### ISSUE THREAD

**Issue by Lightone** [EPIICTHUNDERCAT/ManaWells#3]
i create a few world and try check for that block, but i dont found anyone.

![2017-05-08_09 36 48](https://cloud.githubusercontent.com/assets/2113099/25812802/08115362-33dd-11e7-9f1c-f177454d707c.png)

**Comment by EPIICTHUNDERCAT** [comment]
They're VERY rare and are suppose to be, go in a flat world and try. I tested in multiple worlds, also when you do a bug report always put the version numbers! meaning [1.10.2-0.0.1] or [1.11.2-0.0.1]

Thanks for the report, if you still cannot find one, I will look into it!

**Comment by Lightone** [comment]
sorry for the missing info xD

tested with few mods (1.11.2-0.0.1) and optifine, betterfps, nei and ic2 for nukes, but in flat only found a 2 ,near the spawn point and in lv 2

![2017-05-12_19 45 41](https://cloud.githubusercontent.com/assets/2113099/26021001/d4f7b1b6-374b-11e7-924c-8d3f3c1c95c0.png)

normal world 
if the xp block is generated in the nivel 2 is very hard to found X_X

![2017-05-12_19 11 15](https://cloud.githubusercontent.com/assets/2113099/26021201/95027d9a-374e-11e7-895a-75bcdfb72610.png)

**Comment by EPIICTHUNDERCAT** [comment]
Okay, i knew they spawned! ill look and see if i can turn down the rarity!
